// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByxevd70AT0SlPrws5u5BeuqmLwYoZxeY',
    appId: '1:319941901683:web:40b80140c739225fef1906',
    messagingSenderId: '319941901683',
    projectId: 'flutter-practice-dm',
    authDomain: 'flutter-practice-dm.firebaseapp.com',
    storageBucket: 'flutter-practice-dm.appspot.com',
    measurementId: 'G-5NL5RN4P9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVzVqy58r79cizyzUrlzcdox1UpXhKiww',
    appId: '1:319941901683:android:c97ca8dc7eb5e4baef1906',
    messagingSenderId: '319941901683',
    projectId: 'flutter-practice-dm',
    storageBucket: 'flutter-practice-dm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXTiOgSQSHa5f8aOT032IuuXfJ1wzjFeo',
    appId: '1:319941901683:ios:7b8db09034930cdcef1906',
    messagingSenderId: '319941901683',
    projectId: 'flutter-practice-dm',
    storageBucket: 'flutter-practice-dm.appspot.com',
    iosClientId: '319941901683-n011r4eeiuooc5i2l5tksbga10mi80o5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXTiOgSQSHa5f8aOT032IuuXfJ1wzjFeo',
    appId: '1:319941901683:ios:7b8db09034930cdcef1906',
    messagingSenderId: '319941901683',
    projectId: 'flutter-practice-dm',
    storageBucket: 'flutter-practice-dm.appspot.com',
    iosClientId: '319941901683-n011r4eeiuooc5i2l5tksbga10mi80o5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
